### ISSUE TITLE
Convert relative dates to absolute datetimes

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#91]
An `Article` may have a publication date in datetime format. Dates extracted from text can often be relative or vague, eg. "last Saturday". 

Write a function to Combine `article.Article` publication date with dates interpreted in `report.Report` in order to convert dates extracted from text into datetimes.

**Comment by domingohui** [comment]
Could [this](https://github.com/scrapinghub/dateparser) be an option?

**Comment by domingohui** [comment]
Are we replacing the dates in Reports with new interpreted datetimes? Or are you referring to something like [this](https://github.com/Data4Democracy/internal-displacement/blob/interpreter/internal_displacement/interpreter.py#L403)? In other words, should [datespans](https://github.com/Data4Democracy/internal-displacement/blob/master/internal_displacement/model/model.py#L142) in a Report be an absolute datetime then?

**Comment by domingohui** [comment]
We can have something like 

``` python
def get_absolute_date (a_spacey_token_that_represents_a_date):
    ...
    return datetime(...)
```

And populates a Report using that.

**Comment by simonb83** [comment]
Thanks for all the input @domingohui. I like the idea of a function like that.

Yes we want to convert the 'relative' date strings to absolute dates. The `dateparser` library you mention could be a possibility, although I think there are some cases that it does not cover. From what I have seen the sorts of examples that need to be dealt with are:
- Last Saturday
- 18 May 2015
- Since June 2012

Finally, I'm not sure whether the function should be called by `interpreter.date_likelihood` or perhaps during `Report.__init__` when the report is created.
My main reason is that calling it from `date_likelihood` probably requires passing `publication_date`as an argument to quite a few functions.

What do you think?

**Comment by domingohui** [comment]
Thank you for the feedback, Simon! I thought about calling the new function ```get_absolute_date``` somewhere else like Article and Report too! But looking at the [new schema](https://github.com/Data4Democracy/internal-displacement/blob/interpreter/internal_displacement/model/model.py), those classes seem to be just data models. It would make sense to do that in the old schema. But now it seems kinda awkward to bring up an external package in ```model``` (beside sqlalchemy) while instantiating a ```Report```. 

I agree using the function in [```interpreter.date_likelihood```](https://github.com/Data4Democracy/internal-displacement/blob/interpreter/internal_displacement/interpreter.py#L392) requires more parameter passing. Another sensible location to call it is within ```scraper```. But converting from relative to absolute date is technically an interpreter's job... 

Also, ```Report```s are created in [```interpreter```](https://github.com/Data4Democracy/internal-displacement/blob/interpreter/internal_displacement/interpreter.py#L704). I'm thinking we can call [```interpreter. process_sentence_new```](https://github.com/Data4Democracy/internal-displacement/blob/interpreter/internal_displacement/interpreter.py#L421) with the publication date, which then currently calls [```branch_search_new```](https://github.com/Data4Democracy/internal-displacement/blob/interpreter/internal_displacement/interpreter.py#L617). 
Then we can convert [```possible_dates```](https://github.com/Data4Democracy/internal-displacement/blob/interpreter/internal_displacement/interpreter.py#L626) to absolute dates? And exclude the unlikely dates (too far from publication date or greater than publication date?), and creates ```Report```s afterwards. What do you think?

**Comment by domingohui** [comment]
Just came across [parsedatetime](https://github.com/bear/parsedatetime). It seems to be doing a decent job: (except for formats like ```2000 mar 15```... It got the month and the date correct tho. But I wonder how likely we will come across this format. Tricky things like ```day after tomorrow``` are also not captured. But that's where real, more solid NLP comes in I think!)

They are all relative to today (Mar 14 2017)!

```python
>>> import parsedatetime
>>> cal = parsedatetime.Calendar()
>>> cal.parse("tomorrow")
(time.struct_time(tm_year=2017, tm_mon=3, tm_mday=15, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=74, tm_isdst=-1), 1)
>>> 
>>> cal.parse("since june 2012")
(time.struct_time(tm_year=2012, tm_mon=6, tm_mday=1, tm_hour=23, tm_min=20, tm_sec=48, tm_wday=1, tm_yday=73, tm_isdst=1), 1)

>>> cal.parse("last saturday")
(time.struct_time(tm_year=2017, tm_mon=3, tm_mday=11, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=5, tm_yday=70, tm_isdst=-1), 1)
>>> 
>>> 
>>> cal.parse("last wednesday")
(time.struct_time(tm_year=2017, tm_mon=3, tm_mday=8, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=67, tm_isdst=-1), 1)
>>> 
>>> 
>>> cal.parse("mar 15 2000")
(time.struct_time(tm_year=2000, tm_mon=3, tm_mday=15, tm_hour=23, tm_min=20, tm_sec=0, tm_wday=1, tm_yday=73, tm_isdst=1), 1)
>>> 
>>> 
>>> cal.parse("2000 mar 15 ")
(time.struct_time(tm_year=2017, tm_mon=3, tm_mday=15, tm_hour=20, tm_min=0, tm_sec=0, tm_wday=1, tm_yday=73, tm_isdst=1), 3)

>>> cal.parse("next weekend")
(time.struct_time(tm_year=2017, tm_mon=3, tm_mday=14, tm_hour=23, tm_min=52, tm_sec=34, tm_wday=1, tm_yday=73, tm_isdst=1), 0)

>>> cal.parse("day after tomorrow")
(time.struct_time(tm_year=2017, tm_mon=3, tm_mday=15, tm_hour=9, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=74, tm_isdst=-1), 1)

```

**Comment by simonb83** [comment]
Hey, why don't you go ahead and implement where you think best in `Interpreter`.
We can always go ahead and move it later on if it seems to make sense.

**Comment by simonb83** [comment]
I have added a placeholder `get_absolute_date` in `Interpreter` which can now be updated with enhancements.

Some additional thoughts we had to try and limit the scope of this:
1. Ignore anything in the future
2. If publish date is available, ignore anything X amount of time in the past (i.e. this is the worst storm since 2005 or whatever) ~suggestion is to ignore anything > 1 year ago
3. Try and parse what we're left with as a datetime
4. If we're unable to parse using existing libraries + a little bit of tweaking then ignore for the moment
5. If there are no dates for an article then just use the published date (if available)
